import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-800 text-white text-center p-3 fixed top-0 left-0 w-full">
          Navbar
        </div>

        {children}

        <footer className="bg-gray-800 text-white text-center p-3 fixed bottom-0 left-0 w-full">
          © 2025 My Website. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
